name: Run Unit Tests

# This workflow is triggered on pushes to the repository.
# on: [push]
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Jobs will run in parallel
jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest

    # Steps run synchronously (one after the other)
    steps:
      # Retrieve the codebase on the ubuntu machine.
      # if the codebase isn't required, this step can be skipped.
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build
  test:
    # This job runs on Linux
    runs-on: ubuntu-latest

    # Steps run synchronously (one after the other)
    steps:
      # Retrieve the codebase on the ubuntu machine.
      # if the codebase isn't required, this step can be skipped.
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
      - run: npm test
